### ISSUE TITLE
Concertar bug dos novos scripts

### ISSUE THREAD

**Issue by jr9Hernandez** [rubensolv/GAforMicroRTSCluster#16]
Existe um bug quando algum desstes portfolio joga

'114;57;219;'
'142;152;188;'
'151;245;12;99;'
'169;'
'237;69;'

Detalhe: Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:418)
    at java.util.ArrayList.get(ArrayList.java:431)
    at rts.units.UnitTypeTable.getUnitType(UnitTypeTable.java:241)
    at ai.configurablescript.BehaviorEconomyRushSimple.barracksBehavior(BehaviorEconomyRushSimple.java:163)
    at ai.configurablescript.BehaviorEconomyRushSimple.doEconomyRushSimple(BehaviorEconomyRushSimple.java:74)

**Comment by rubensolv** [comment]
Corrigido.
